-- ==========================================
-- EMOJI MARKET - SUPABASE POSTGRESQL DDL SCHEMA
-- ==========================================

-- 1. web3_users 테이블 생성 (Web3 지갑 기반 유저 관리)
CREATE TABLE IF NOT EXISTS public.web3_users (
    wallet_address TEXT PRIMARY KEY,
    nonce TEXT NOT NULL,
    nonce_expires_at TIMESTAMPTZ NOT NULL,
    nickname TEXT DEFAULT 'MCI_User_' || substr(md5(random()::text), 1, 8),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 코멘트 추가
COMMENT ON COLUMN public.web3_users.wallet_address IS '소문자로 표준화된 이더리움/폴리곤 지갑 주소';
COMMENT ON COLUMN public.web3_users.nonce IS '리플레이 공격 방지용 5분 만료 일회성 난스 토큰';

-- 2. emojis 테이블 생성 (이모티콘 파일 메타데이터 및 NFT 소유권 관리)
CREATE TABLE IF NOT EXISTS public.emojis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT gen_random_uuid() NOT NULL,
    creator_wallet TEXT REFERENCES public.web3_users(wallet_address) ON DELETE SET NULL,
    owner_wallet TEXT REFERENCES public.web3_users(wallet_address) ON DELETE SET NULL,
    style_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    is_nft BOOLEAN DEFAULT false,
    nft_token_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 기본값 설정: owner_wallet이 명시되지 않으면 creator_wallet과 동일하게 세팅
ALTER TABLE public.emojis ALTER COLUMN owner_wallet SET DEFAULT NULL;

-- 3. preorders 테이블 생성 (희귀 이모티콘 사전 예약 목록)
CREATE TABLE IF NOT EXISTS public.preorders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT UNIQUE NOT NULL,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 인덱스(Indices) 생성 (조회 속도 및 성능 최적화)
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_emojis_uuid ON public.emojis(uuid);
CREATE INDEX IF NOT EXISTS idx_emojis_owner_wallet ON public.emojis(owner_wallet);

-- ==========================================
-- RLS (Row Level Security) 및 보안 정책 설정
-- ==========================================

-- RLS 활성화
ALTER TABLE public.web3_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emojis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preorders ENABLE ROW LEVEL SECURITY;

-- 1) web3_users RLS Policy
-- 백엔드(Service Role) 외에, 일반 익명 유저는 서명 인증 전 난스 획득을 위해 본인 지갑 레코드를 Select 하거나 Upsert 할 수 있도록 설정
CREATE POLICY "Allow public select web3_users by address" ON public.web3_users
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public upsert web3_users" ON public.web3_users
    FOR ALL TO public USING (true) WITH CHECK (true);

-- 2) emojis RLS Policy
-- DRM 보안 가이드라인 준수: 모든 파일 생성 및 다운로드는 Next.js API (Service Role)를 통해서만 안전하게 중계되므로
-- public(비인증 익명)에 대한 직접적인 조회를 차단하고 오직 Service Role만 모든 접근 권한 허용
CREATE POLICY "Allow full access for service_role only" ON public.emojis
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- (폴백용) 클라이언트 직접 쿼리 허용할 경우: 본인이 소유한 이모지만 Select 허용
CREATE POLICY "Allow select if owner matches wallet" ON public.emojis
    FOR SELECT TO public USING (owner_wallet = current_setting('request.headers', true)::json->>'x-wallet-address');

-- 3) preorders RLS Policy
-- 누구나 사전 예약을 신청(Insert)할 수 있으나, 조회는 불가능하게 통제
CREATE POLICY "Allow public insert preorders" ON public.preorders
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow service_role full control on preorders" ON public.preorders
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ==========================================
-- STORAGE BUCKET SETUP GUIDE & STORAGE RLS SQL
-- ==========================================
/*
   [Supabase Storage Private 'emojis' 버킷 세팅 방법]
   
   1. Supabase Dashboard 좌측 메뉴에서 'Storage' 선택
   2. 'New Bucket' 클릭 -> 버킷 이름을 'emojis'로 설정
   3. 'Public Bucket' 토글을 비활성화(Private 상태 유지)하여 비인증 사용자의 파일 Direct URL 주소 접근을 원천 차단
   4. 아래 SQL 정책 스크립트를 실행하여 Storage RLS 설정 적용:
*/

-- Storage RLS 정책: emojis 버킷에 대해 오직 service_role(Next.js 백엔드)만 다운로드 및 업로드 허용
-- 일반 브라우저에서 직접 파일 URL(storage/v1/object/public/...)로 요청할 경우 Access Denied가 발생하게 차단
CREATE POLICY "Block direct file access on emojis bucket" ON storage.objects
    FOR SELECT TO public USING (bucket_id = 'emojis' AND auth.role() = 'service_role');

CREATE POLICY "Allow service_role upload to emojis bucket" ON storage.objects
    FOR INSERT TO service_role WITH CHECK (bucket_id = 'emojis');
