-- ==========================================
-- EMOJI MARKET - SUPABASE POSTGRESQL DDL SCHEMA
-- ==========================================

-- 1. web3_users 테이블 생성 (Web3 지갑 기반 유저 관리)
CREATE TABLE IF NOT EXISTS public.web3_users (
    wallet_address TEXT PRIMARY KEY,
    nonce TEXT NOT NULL,
    nonce_expires_at TIMESTAMPTZ NOT NULL,
    nickname TEXT DEFAULT 'MCI_User_' || substr(md5(random()::text), 1, 8),
    points INTEGER DEFAULT 3,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    kakao_id TEXT UNIQUE,
    real_name TEXT,
    push_subscription JSONB,
    pending_emoji_notifications INTEGER DEFAULT 0,
    profile_image_url TEXT,
    status TEXT DEFAULT 'active'
);

-- 코멘트 추가
COMMENT ON COLUMN public.web3_users.wallet_address IS '소문자로 표준화된 이더리움/폴리곤 지갑 주소';
COMMENT ON COLUMN public.web3_users.nonce IS '리플레이 공격 방지용 5분 만료 일회성 난스 토큰';
COMMENT ON COLUMN public.web3_users.points IS '이모티콘 생성용 포인트 잔액 (웰컴 3P 지급)';
COMMENT ON COLUMN public.web3_users.kakao_id IS '카카오 소셜 회원 로그인 고유 ID 매핑';
COMMENT ON COLUMN public.web3_users.real_name IS '카카오 본인인증 검증 실제 실명';
COMMENT ON COLUMN public.web3_users.push_subscription IS '웹 푸시 브라우저 고유 키 저장용';
COMMENT ON COLUMN public.web3_users.pending_emoji_notifications IS '미확인 완성 세트 개수';
COMMENT ON COLUMN public.web3_users.profile_image_url IS '카카오 고해상도 프로필 이미지 저장';
COMMENT ON COLUMN public.web3_users.status IS '유저 계정 활성화 상태';

-- 2. emojis 테이블 생성 (이모티콘 파일 메타데이터 및 NFT 소유권 관리)
CREATE TABLE IF NOT EXISTS public.emojis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE DEFAULT gen_random_uuid() NOT NULL,
    creator_wallet TEXT REFERENCES public.web3_users(wallet_address) ON DELETE SET NULL,
    owner_wallet TEXT REFERENCES public.web3_users(wallet_address) ON DELETE SET NULL,
    style_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    is_nft BOOLEAN DEFAULT false,
    nft_token_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'completed',
    is_viewed BOOLEAN DEFAULT true
);

-- 기본값 설정: owner_wallet이 명시되지 않으면 creator_wallet과 동일하게 세팅
ALTER TABLE public.emojis ALTER COLUMN owner_wallet SET DEFAULT NULL;

-- 3. preorders 테이블 생성 (희귀 이모티콘 사전 예약 목록)
CREATE TABLE IF NOT EXISTS public.preorders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT UNIQUE NOT NULL,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ==========================================
-- 인덱스(Indices) 생성 (조회 속도 및 성능 최적화)
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_emojis_uuid ON public.emojis(uuid);
CREATE INDEX IF NOT EXISTS idx_emojis_owner_wallet ON public.emojis(owner_wallet);

-- ==========================================
-- RLS (Row Level Security) 및 보안 정책 설정
-- ==========================================

-- RLS 활성화
ALTER TABLE public.web3_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emojis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preorders ENABLE ROW LEVEL SECURITY;

-- 1) web3_users RLS Policy
-- 백엔드(Service Role) 외에, 일반 익명 유저는 서명 인증 전 난스 획득을 위해 본인 지갑 레코드를 Select 하거나 Upsert 할 수 있도록 설정
CREATE POLICY "Allow public select web3_users by address" ON public.web3_users
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public upsert web3_users" ON public.web3_users
    FOR ALL TO public USING (true) WITH CHECK (true);

-- 2) emojis RLS Policy
-- DRM 보안 가이드라인 준수: 모든 파일 생성 및 다운로드는 Next.js API (Service Role)를 통해서만 안전하게 중계되므로
-- public(비인증 익명)에 대한 직접적인 조회를 차단하고 오직 Service Role만 모든 접근 권한 허용
CREATE POLICY "Allow full access for service_role only" ON public.emojis
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- (폴백용) 클라이언트 직접 쿼리 허용할 경우: 본인이 소유한 이모지만 Select 허용
CREATE POLICY "Allow select if owner matches wallet" ON public.emojis
    FOR SELECT TO public USING (owner_wallet = current_setting('request.headers', true)::json->>'x-wallet-address');

-- 3) preorders RLS Policy
-- 누구나 사전 예약을 신청(Insert)할 수 있으나, 조회는 불가능하게 통제
CREATE POLICY "Allow public insert preorders" ON public.preorders
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow service_role full control on preorders" ON public.preorders
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- 4. point_transactions 테이블 생성 (포인트 충전/사용 내역 추적)
CREATE TABLE IF NOT EXISTS public.point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT REFERENCES public.web3_users(wallet_address) ON DELETE CASCADE NOT NULL,
    amount INTEGER NOT NULL,
    transaction_type TEXT NOT NULL, -- 'charge', 'use', 'gift'
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS 활성화 및 정책 설정
ALTER TABLE public.point_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select point_transactions" ON public.point_transactions
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert point_transactions" ON public.point_transactions
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow service_role control on point_transactions" ON public.point_transactions
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ==========================================
-- STORAGE BUCKET SETUP GUIDE & STORAGE RLS SQL
-- ==========================================
/*
   [Supabase Storage Private 'emojis' 버킷 세팅 방법]
   
   1. Supabase Dashboard 좌측 메뉴에서 'Storage' 선택
   2. 'New Bucket' 클릭 -> 버킷 이름을 'emojis'로 설정
   3. 'Public Bucket' 토글을 비활성화(Private 상태 유지)하여 비인증 사용자의 파일 Direct URL 주소 접근을 원천 차단
   4. 아래 SQL 정책 스크립트를 실행하여 Storage RLS 설정 적용:
*/

-- Storage RLS 정책: emojis 버킷에 대해 오직 service_role(Next.js 백엔드)만 다운로드 및 업로드 허용
-- 일반 브라우저에서 직접 파일 URL(storage/v1/object/public/...)로 요청할 경우 Access Denied가 발생하게 차단
CREATE POLICY "Block direct file access on emojis bucket" ON storage.objects
    FOR SELECT TO public USING (bucket_id = 'emojis' AND auth.role() = 'service_role');

CREATE POLICY "Allow service_role upload to emojis bucket" ON storage.objects
    FOR INSERT TO service_role WITH CHECK (bucket_id = 'emojis');


-- ==========================================
-- 5. 추천인(레퍼럴) 보상 포인트 시스템 관련 DDL 마이그레이션
-- ==========================================

-- 1) web3_users 테이블에 추천 코드 및 상태 필드 추가
ALTER TABLE public.web3_users ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
ALTER TABLE public.web3_users ADD COLUMN IF NOT EXISTS referred_by TEXT REFERENCES public.web3_users(wallet_address);
ALTER TABLE public.web3_users ADD COLUMN IF NOT EXISTS referral_count INTEGER DEFAULT 0;

-- 2) 신규 가입 유저 발생 시 6자리의 고유 대문자 추천 코드를 자동으로 생성하는 DB 트리거 함수
CREATE OR REPLACE FUNCTION generate_unique_referral_code()
RETURNS TRIGGER AS $$
DECLARE
    new_code TEXT;
    done BOOLEAN := FALSE;
BEGIN
    WHILE NOT done LOOP
        -- 대문자와 숫자가 섞인 6자리 랜덤 코드 생성 (예: EMOJ1A, F8D2K9)
        new_code := upper(substring(md5(random()::text) from 1 for 6));
        -- 중복 검증
        IF NOT EXISTS (SELECT 1 FROM public.web3_users WHERE referral_code = new_code) THEN
            done := TRUE;
        END IF;
    END LOOP;
    NEW.referral_code := new_code;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3) 유저 가입 전 추천 코드 자동 매핑 트리거 생성
CREATE OR REPLACE TRIGGER trigger_generate_referral_code
BEFORE INSERT ON public.web3_users
FOR EACH ROW
WHEN (NEW.referral_code IS NULL)
EXECUTE FUNCTION generate_unique_referral_code();


-- ==========================================
-- 6. P2P 마켓플레이스 및 거래 테이블 DDL 마이그레이션
-- ==========================================

-- 1) P2P 마켓플레이스 판매 등록 테이블 생성
CREATE TABLE IF NOT EXISTS public.emoji_market_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emoji_id BIGINT REFERENCES public.emojis(id) ON DELETE CASCADE,
    seller_wallet TEXT REFERENCES public.web3_users(wallet_address) ON DELETE CASCADE,
    price INTEGER NOT NULL CHECK (price > 0),
    status TEXT DEFAULT 'active' NOT NULL, -- 'active', 'sold', 'cancelled'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2) 거래 내역 로그 테이블 생성
CREATE TABLE IF NOT EXISTS public.emoji_trade_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.emoji_market_listings(id) ON DELETE SET NULL,
    emoji_id BIGINT REFERENCES public.emojis(id) ON DELETE CASCADE,
    seller_wallet TEXT NOT NULL,
    buyer_wallet TEXT NOT NULL,
    price INTEGER NOT NULL,
    fee INTEGER NOT NULL, -- 플랫폼 수수료 (5%)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS 활성화 및 권한 설정 (P2P 장터 조회는 public 개방)
ALTER TABLE public.emoji_market_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emoji_trade_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select emoji_market_listings" ON public.emoji_market_listings
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role full control on listings" ON public.emoji_market_listings
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Allow public select emoji_trade_history" ON public.emoji_trade_history
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow service_role control on history" ON public.emoji_trade_history
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ==========================================
-- 7. 어뷰징 제재 및 블랙리스트 상태 관리 필드 추가
-- ==========================================

-- web3_users 테이블에 상태 필드가 없으면 기본값 'active'로 추가
ALTER TABLE public.web3_users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('active', 'blocked'));

-- 인덱스 추가로 어뷰저 실시간 쿼리 속도 최적화
CREATE INDEX IF NOT EXISTS idx_users_status_created ON public.web3_users(status, created_at);

-- web3_users 테이블 RLS 활성화 및 익명/인증 사용자 무제한 접근 허용 정책 (회원가입 에러 예방)
ALTER TABLE public.web3_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anonymous and authenticated users access to web3_users" ON public.web3_users;
CREATE POLICY "Allow anonymous and authenticated users access to web3_users" 
ON public.web3_users FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);



